# SPDX-License-Identifier: Apache-2.0
"""ADR-019 declarative pricing + HMAC-SHA256 signing — provider-side.

Port of iicp-adapter's `security/signing.py` + `services/registry._pricing_block`
(iter-1410) into the iicp-client-python SDK. Tier 2 Item 3 of the
iicp-adapter → iicp-client migration (tracker iicp.network#340).

Operators declare a per-node pricing block at registration time:

  - `credit_cost_multiplier` — float ≥ 0 applied to base rate; default 1.0
  - `pricing_model` — currently only `"per_token"` is defined in v1
  - `effective_from`, `effective_until` — optional ISO-8601 window
  - `declaration_signature` — HMAC-SHA256 over canonical-JSON of
                              {credit_cost_multiplier, pricing_model} sorted

When the operator opts in (`sign_declarations=True`) AND a `node_hmac_key`
is provisioned (returned by the directory on register), the SDK includes
`declaration_signature` in the register payload. The directory verifies
with the same HMAC; mismatch → IICP-E010. ADR-012 §10.4 mandates this
integrity step for CIP cooperative sessions.

Pricing is OPT-IN to keep the safe-by-default story consistent with CIP:
nodes that don't declare pricing get the directory's default multiplier
(1.0) and a `pricing.attested=false` annotation in /v1/discover.
"""
from __future__ import annotations

import hashlib
import hmac
import json
from dataclasses import dataclass
from typing import Any


@dataclass
class PricingConfig:
    """ADR-019 pricing declaration block (operator-controlled).

    All defaults reproduce the adapter's PricingConfig contract so wire
    behaviour is identical between adapter and hybrid clients.
    """
    credit_cost_multiplier: float = 1.0
    pricing_model: str = "per_token"
    # When True AND a node_hmac_key is set on the node, the SDK signs the
    # pricing block before sending it in the register payload. The directory
    # verifies and surfaces `pricing.attested=true` in /v1/discover.
    sign_declarations: bool = False
    effective_from: str | None = None
    effective_until: str | None = None


# ── HMAC helpers ────────────────────────────────────────────────────────────

def sign_body(body: bytes, secret: str) -> str:
    """HMAC-SHA256 hex digest — matches the directory's
    `hash_hmac('sha256', $body, $key)` and the adapter's `sign_body`."""
    return hmac.new(secret.encode(), body, hashlib.sha256).hexdigest()


def verify_signature(body: bytes, secret: str, signature: str) -> bool:
    """Constant-time signature comparison. Returns True when the HMAC matches."""
    expected = sign_body(body, secret)
    return hmac.compare_digest(expected, signature)


def _php_canonical_sign_body(*, credit_cost_multiplier: float, pricing_model: str) -> bytes:
    """Encode the pricing-block signature body the way the directory's PHP
    json_encode does, so HMAC verification succeeds across the language gap.

    PHP behaviour we need to replicate:
      - keys sorted alphabetically (`ksort`)
      - whole-float values are emitted WITHOUT a fractional zero, i.e.
        json_encode(1.0) → "1"   (Python json.dumps(1.0) defaults to "1.0")
      - non-whole floats use the natural decimal representation
      - no whitespace (PHP json_encode default + Python separators=",":)

    Signatures generated by this helper match
    `hash_hmac('sha256', json_encode(ksort($body)), $key)` in PHP byte-for-byte.
    """
    def fmt_number(v: float) -> str:
        # PHP json_encode collapses whole floats to integer form. Mimic that.
        if isinstance(v, bool):
            return "true" if v else "false"
        if isinstance(v, int):
            return str(v)
        if v == int(v):
            return str(int(v))
        # Non-whole: rely on Python's repr (matches PHP's default float
        # rendering for the precision range pricing uses; if operators need
        # exotic precision they should send int-multiplied values).
        return repr(v)

    parts = [
        f'"credit_cost_multiplier":{fmt_number(credit_cost_multiplier)}',
        f'"pricing_model":{json.dumps(pricing_model)}',
    ]
    return ("{" + ",".join(parts) + "}").encode()


# ── Pricing-block payload ──────────────────────────────────────────────────

def build_pricing_block(pricing: PricingConfig, hmac_key: str = "") -> dict[str, Any]:
    """Construct the `pricing` sub-object the directory accepts in /v1/register.

    Spec contract (directory `NodeRegistry::resolvePricingBlock`):
      - signature body is the JSON-encoded {credit_cost_multiplier, pricing_model}
        with sorted keys (no whitespace fluff — `json.dumps(..., sort_keys=True)`)
      - signature is sent in `declaration_signature` ONLY when
        `sign_declarations=True` AND the operator has provisioned a `hmac_key`

    Empty `hmac_key` with `sign_declarations=True` is a no-op — the block is
    sent unsigned. The directory will still accept it; `pricing.attested` ends
    up `false` in /v1/discover, which is the correct un-attested signal.
    """
    block: dict[str, Any] = {
        "credit_cost_multiplier": pricing.credit_cost_multiplier,
        "pricing_model": pricing.pricing_model,
    }
    if pricing.sign_declarations and hmac_key:
        body = _php_canonical_sign_body(
            credit_cost_multiplier=pricing.credit_cost_multiplier,
            pricing_model=pricing.pricing_model,
        )
        block["declaration_signature"] = sign_body(body, hmac_key)
    if pricing.effective_from is not None:
        block["effective_from"] = pricing.effective_from
    if pricing.effective_until is not None:
        block["effective_until"] = pricing.effective_until
    return block
